Tenant mongodb
decentralized-cloud/tenant pull request #78
Opened 2019-10-30 22:15 UTC by morteza-azizi

2019-11-02 06:23 UTC, mortezaalizadeh requested changes

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +
Need to add "defer client.Disconnect(ctx)" here

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +
Need to add "defer client.Disconnect(ctx)" here

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +
Need to add "defer client.Disconnect(ctx)" here

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +
Need to add "defer client.Disconnect(ctx)" here

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		collectionName:       "tenants",
this does not have to be in the service context, it defines the collection name and will be same for all instances, can be defined simply as a const variable on the top of the file

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +	dbConnectionString, err := service.configurationService.GetDbConnectionString()
Read the connection string once on top of the file and just add the connection string to the service context, no need to read it each time by accessing the config service

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		configurationService: configurationService,
just read the connection string once and only keep the reference to that as part of the service context, no need to keep the reference to the configuration service here

also, read the name of the database here, no need to keep reading it using configuration service

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		return nil, commonErrors.NewArgumentNilError("GetDbConnectionString", "Database connection String is required.")
when you receive the error, wrap it as part of the returned error

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		return nil, commonErrors.NewArgumentNilError("GetTenantDbName", "Database name is required.")
when you receive the error, wrap it as part of the returned error

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		return nil, repository.NewTenantNotFoundError(request.TenantID)
when you receive the error, wrap it as part of the returned error

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		return nil, commonErrors.NewArgumentNilError("GetDbConnectionString", "Database connection String is required.")
when you receive the error, wrap it as part of the returned error

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		return nil, commonErrors.NewArgumentNilError("GetTenantDbName", "Database name is required.")
when you receive the error, wrap it as part of the returned error

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		return nil, commonErrors.NewArgumentNilError("GetDbConnectionString", "Database connection String is required.")
when you receive the error, wrap it as part of the returned error

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		return nil, commonErrors.NewArgumentNilError("GetTenantDbName", "Database name is required.")
when you receive the error, wrap it as part of the returned error

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		return nil, commonErrors.NewArgumentNilError("GetDbConnectionString", "Database connection String is required.")
when you receive the error, wrap it as part of the returned error

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +		return nil, commonErrors.NewArgumentNilError("GetTenantDbName", "Database name is required.")
when you receive the error, wrap it as part of the returned error

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +	response, err := collection.DeleteOne(context.TODO(), filter)
don't use context.TODO, use the provided context

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service.go
> +	response := &repository.SearchResponse{}
Need to implement the search function!!!

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service_test.go
> +					Return(expectedTenantDbName, nil)
Do this once on the root BeforeEach function, no need to repeat it in each test

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service_test.go
> +					Return(expectedTenantDbName, nil)
Do this once on the root BeforeEach function, no need to repeat it in each test

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service_test.go
> +					Return(expectedTenantDbName, nil)
Do this once on the root BeforeEach function, no need to repeat it in each test

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service_test.go
> +					Return(expectedTenantDbName, nil)
Do this once on the root BeforeEach function, no need to repeat it in each test

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service_test.go
> +					Return(expectedTenantDbName, nil)
Do this once on the root BeforeEach function, no need to repeat it in each test

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service_test.go
> +
Do this once on the root BeforeEach function, no need to repeat it in each test

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service_test.go
> +					Return(expectedTenantDbName, nil)
Do this once on the root BeforeEach function, no need to repeat it in each test

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service_test.go
> +					Return(expectedTenantDbName, nil)
Do this once on the root BeforeEach function, no need to repeat it in each test

2019-11-02 06:23 UTC, mortezaalizadeh commented on services/repository/mongodb/service_test.go
> +					Return(expectedTenantDbName, nil)
Do this once on the root BeforeEach function, no need to repeat it in each test

2019-11-03 09:44 UTC, alir14 approved these changes

2019-11-03 09:47 UTC, merged